### ISSUE TITLE
Sobre o Banco Orientado a Grafos

### ISSUE THREAD

**Issue by joaovictor-1** [Werricsson-Santos/NoSQL-Neo4J-Atividade-Pratica-Tweets#1]
Como criou seu nome relacionado com sua RU, amigo?

**Comment by Werricsson-Santos** [comment]
> Como criou seu nome relacionado com sua RU, amigo?

Acredito que achou lá né amigo?
Se não me engano, na resposta 1 está na linha 48 (diretório "Populando o banco e consultas"). 
Basta criar um nodo para o seu nome e outro para o RU, relacionando eles...
